### PR TITLE
Run perf tests in their own threads

### PR DESCRIPTION
**Pull request by azureskydiver**
It was sad to see almost all the other cores of my PC running idle while each benchmark ran sequentially 3 seconds at a time. This takes advantage of the idle cores.

### CODE REVIEW

**Comment by Xor-el** [comment]
thanks for this pull request, I appreciate it a lot, I can assert that the benchmarks runs a lot faster.
merged.

**Comment by azureskydiver** [comment]
They actually finish faster but have slower  throughput on my old machine 
(likely because of the poor bus architecture on the older AMD chipsets). 
They do seem to have better throughput on my new-ish AMD based laptop, but 
I think it's because AMD got it's act together, and because with all cores 
being busy, the cores are not slowing down to a lower frequency.

**Comment by Xor-el** [comment]
> 
> They actually finish faster but have slower throughput on my old machine (likely because of the poor bus architecture on the older AMD chipsets). They do seem to have better throughput on my new-ish AMD based laptop, but I think it's because AMD got it's act together, and because with all cores being busy, the cores are not slowing down to a lower frequency.
> […](#)
> On May 30, 2020 20:43:18 Ugochukwu Mmaduekwe ***@***.***> wrote: thanks for this pull request, I appreciate it a lot, at least I can assert that the benchmarks run faster. merged.— You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, you are right, one workaround I found though is running a single hash benchmark at a time. that way, only one task is started.

**Comment by azureskydiver** [comment]
Yup, I'm doing the same for just quick tests on my old machine. The new 
machine keeps frequencies down for just a single core being pushed.

I tried to follow the logic of the Blake 3 implementation, but the use of 
side effects to update the CV  makes things harder to follow. There also 
seems to be some logic which constructs nodes and just throws then away 
since all it wanted was the CV to put into the CV stack, but it does not 
take advantage of the previously computed node in the chunk state.

Right now, my gut feel is that part of the slowdown is all that moving of 
data from the incoming stream, then into the chunk state block, then into 
the node in the chunk state node block just to compute a CV. If the number 
of moves could be minimized, I think some gains can be made.

**Comment by Xor-el** [comment]
> 
> Yup, I'm doing the same for just quick tests on my old machine. The new machine keeps frequencies down for just a single core being pushed. I tried to follow the logic of the Blake 3 implementation, but the use of side effects to update the CV makes things harder to follow. There also seems to be some logic which constructs nodes and just throws then away since all it wanted was the CV to put into the CV stack, but it does not take advantage of the previously computed node in the chunk state. Right now, my gut feel is that part of the slowdown is all that moving of data from the incoming stream, then into the chunk state block, then into the node in the chunk state node block just to compute a CV. If the number of moves could be minimized, I think some gains can be made.
> […](#)
> On May 31, 2020 02:03:17 Ugochukwu Mmaduekwe ***@***.***> wrote: They actually finish faster but have slower throughput on my old machine (likely because of the poor bus architecture on the older AMD chipsets). They do seem to have better throughput on my new-ish AMD based laptop, but I think it's because AMD got it's act together, and because with all cores being busy, the cores are not slowing down to a lower frequency. … On May 30, 2020 20:43:18 Ugochukwu Mmaduekwe @.***> wrote: thanks for this pull request, I appreciate it a lot, at least I can assert that the benchmarks run faster. merged.— You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. yes, you are right, one workaround I found though is running a single hash benchmark at a time. that way, only one task is started. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks for taking a look at the Blake3 implementation.
your statements are right, my code is quite similar to the original reference implementation.
unfortunately, the optimized rust implementation was quite difficult for me to follow especially with the whole multi-threaded integration.

**Pull request merged**
